apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: healthchecks.webapp.udaykk.me
spec:
  group: webapp.udaykk.me
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
  scope: Namespaced
  names:
    kind: Healthcheck
    plural: healthchecks   # Specify the plural name
    singular: healthcheck  # Specify the singular name
  subresources:
    status: {}
